# Generated by Django 3.1.5 on 2022-02-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
